### ISSUE TITLE
ludown refresh mangles special characters

### ISSUE THREAD

**Issue by EdwinOtten** [microsoft/botframework-cli#157] opened 2019-09-24 10:02 UTC
## Tool
Name: Ludown
Version: 1.3.3
OS: Windows 10

## Describe the bug
This is possibly related to issue microsoft/botbuilder-tools#1072 , so I double checked that I am on the latest version (I'm on 1.3.3).

When a LUIS application contains special characters, the `ludown refresh` command creates a LU file that mangles those characters. I am experiencing this when using the the `--RemoteToLocal` option of [update_cognitive_models.ps1](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1).

## To Reproduce
Steps to reproduce the behaviour:
1. Create a LUIS application with utterances that contain characters like `è é ö` 
2. Export the LUIS model with `luis export version` and use that as an input stream for `ludown refresh` (this is how [update_cognitive_models.ps1](https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Template/VA/Deployment/Scripts/update_cognitive_models.ps1) does it, around line 48).
3. Check the resulting .lu file, which now contains mangled characters

## Expected behavior
The resulting .lu file should contain texts from the LUIS model as-is. So `ö` in the .json export look like `ö` in the generated .lu file.

## Examples
This is what happens:
```
- éénvlaksvulling
- ├⌐├⌐nvlaksvulling 

- bètablokker
- b├¿tablokker   

- danke schön
- danke sch├╢n 
```

[bug]

**Comment by vishwacsena** [comment] 2019-09-25 01:40
@munozemilio can you help take a look? FWIW, this appears to be related to the read-text-file change you'd worked on.

**Comment by munozemilio** [comment] 2019-09-25 17:18
We will investigate and find the issue soon. This fix should be part of the new bf cli tool

**Comment by munozemilio** [comment] 2019-09-27 00:29
Hello @EdwinOtten ... I tried to reproduce with fresh install of ludown, and the new ludown tool (called luis) but I got no error:
json fragment ---------------
  "utterances": [
    {
      "text": "éénvlaksvulling",
      "intent": "None",
      "entities": []
    },
    {
      "text": "bètablokker",
      "intent": "None",
      "entities": []
    },
    {
      "text": "danke schön",
      "intent": "None",
      "entities": []
    },
----------------------------
output
----------------------------
## None
- éénvlaksvulling
- bètablokker
- danke schön

I ran the command like this: ludown refresh -i file.json are you passing any other params?
Probably can you try uninstalling and installing ludown again?
@lauren-mills FYI

**Comment by EdwinOtten** [comment] 2019-09-27 11:44
Hi @munozemilio, thank you for looking into this! 
I have digged down a little more and found that the characters are getting malformed earlier in the process, during `luis export version`.

When exporting it via the LUIS portal, the .json looks fine. When I export it via the luis cli tool (v2.6.2), the bug appears.

So it's an issue with luis cli, **not** with ludown.

## How to reproduce
1. Create a LUIS app with utterances that characters like `è é ö`
2. Install the latest luis cli: `npm install -g luis-apis`
3. Export the LUIS model to json using the following command:
```
luis export version `
    --appId YOUR_LUIS_APP_ID_HERE `
    --versionId 0.1 `
    --authoringKey YOUR_AUTHORING_KEY_HERE `
    > "luis_2.6.2_export.json"
```

The result is:
```
  "utterances": [
    {
      "text": "b├¿tablokker",
      "intent": "None",
      "entities": []
    },
    {
      "text": "danke sch├╢n",
      "intent": "None",
      "entities": []
    },
    {
      "text": "├⌐├⌐nvlaksvulling",
      "intent": "None",
      "entities": []
    }
  ],
```

**Comment by munozemilio** [comment] 2019-09-27 21:47
Hi @EdwinOtten, thank you for investing extra time on this.
I went ahead and tested exactly as you mentioned but I kept getting the correct result. I wonder if you could test in cmd directly. In the other hand I found this [reference](https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell) that mention a probably root cause. Let me know if that works for you.

**Comment by EdwinOtten** [comment] 2019-09-30 07:42
> I wonder if you could test in cmd directly.

I ran the command again, once in PS and once in CMD. Indeed, in CMD it works! So something goes wrong in PS..

Some more info:
- Windows 10 Enterprise (version 1903, OS Build 18362.267)
- PowerShell 6.2.3
- LUIS cli 2.6.2

---

> In the other hand I found this [reference](https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell) that mention a probably root cause. Let me know if that works for you.

Would it help if I try the TrueType configuration suggested below **Making your Windows PowerShell console window Unicode (UTF-8) aware**?

**Comment by munozemilio** [comment] 2019-09-30 22:15
Hi @EdwinOtten, yes please, try the configuration and hopefully that will solve the issue. I will close this issue since it is no related to ludown but feel to reach out in case I can help with something else.

**Closed by munozemilio** 2019-09-30 22:15 UTC
Labels: 4.6, customer-replied-to, customer-reported, lu

**Comment by EdwinOtten** [comment] 2019-10-01 14:52
I was able to solve this issue based on the answers on stackoverflow. This could be valuable for others running into this issue:

1. The [reference](https://stackoverflow.com/a/49481797/1644624) mentions configuring Powershell to use a *UTF-8 compatible TrueType font*. In my case (Windows 10) it was set to Consolas by default, which already supports UTF-8 characters like `è é ö`. So I didn't have to change anything here.

2. The instructions also say to change the codepage. So I tried to do that by running the suggested command: 
```
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding =
                    New-Object System.Text.UTF8Encoding
```
This fixed the issue for me. However... this command only sets the output encoding for the **current** Powershell session.

If you use the latest version of Windows 10, there is a beta feature that sets codepage for you (without having to execute the command above every time). You can read how to do this [here](https://stackoverflow.com/a/57134096/1644624).

---

@munozemilio Should I create an issue for this in the LUIS cli repository? Or is this a *configuration error* that cannot be fixed?

**Comment by sgellock** [comment] 2019-10-01 16:31
@EdwinOtten based on our investigation of the issue you reported, we believe this is an issue with PowerShell.  So it's our recommendation that you log an issue with them, so they can address the issue on their side.  Here is their GH repo:  https://github.com/PowerShell/PowerShell

**Comment by EdwinOtten** [comment] 2019-11-04 14:42
**Follow-up:** I found that someone already filed [a Feature Request](https://github.com/PowerShell/PowerShell/issues/7233) with the Powershell team. So I gave that issue a 👍to support it.
