### ISSUE TITLE
Packages with declarative files

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-cli#1202] opened 2021-04-15 01:17 UTC
## Describe the bug

Installing packages is ignoring declarative files unless they are a full set of files (including the extraneous empty ones) for a dialog, and are contained within an `exported` folder in the package.

Attached is an example package, that has:

1. 2 .lg files at the root of the package
2. A .dialog file at the root of the package
3. A "full" set of files in the /FeedbackDialog folder
4. A "full" set of files in the /exported/ChitChatDialog folder

If you import this package, you'll observe that only the ChitChatDialog is added to Composer, the rest of the declarative files are ignored.

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Download the attached .zip file
2. Change the file extension to .nupkg
3. Add to a local feed (nuget add <package> -source "c:\someplace\feed")
4. Create/open a bot in Composer
5. In package manager, add your local feed
6. Install the package (MyPackage)
7. Observe that only the complete dialog package in the 'exported' folder was added to Composer

## Expected behavior

The declarative files are imported, regardless of where they are in the package.

- The .lg files should be available in the Bot Responses tab.
- The .dialog files should be available as dialogs.
- If the declarative files are in a non-functional state, they should still be imported and Composer should flag them as needing attention.

## Additional context

[MyPackage.1.0.0.zip](https://github.com/microsoft/BotFramework-Composer/files/6314659/MyPackage.1.0.0.zip)

**Comment by chrimc62** [comment] 2021-04-16 15:42
This is by design.  The issue is that you want the package creator to have control of what is exposed to be customized and what is "implementation details" of some feature.

**Comment by clearab** [comment] 2021-04-16 16:10
I don't understand what this means - if the declarative files aren't merged how could they be part of the implementation details?

**Comment by clearab** [comment] 2021-04-16 16:12
As someone creating packages, I absolutely need to be able to just drop a .qna file, or a .lu file, in a package, and have it get merged and be available for my users to consume and use. There is not a requirement that the declarative assets I include in my package are in a special folder, or that they be a complete dialog set.

**Comment by chrimc62** [comment] 2021-04-16 16:26
Should I be able to control what people can customize in my package?  Programming languages let you control what is internal to your package and what gets exported, why should this be any different?  You can take an adaptive dialog and create a .schema for it and it becomes a component you can use in composer--you might not want to expose all parts of the implementation because you don't want to support them or you plan to change them.
I think what you are really complaining about is that you want to make the act of creating packages easier and on that I entirely agree.  I would love to add to the bf cli a package command that you can point to a dialog and get it all packaged up including the nuget/package.json.

**Comment by clearab** [comment] 2021-04-16 18:57
The use case I'd like to support is: I'm an ISV. I have a set of .lg files that I re-use constantly between clients. I want to make a package for my organization's use that allows me to easily re-use the that .lg file. I have no need for complete dialogs, nor do I want to put it in any special folders. I just want to make a package for my 10 .lg files, then have them appear in the bot responses tab and be able to reference them from new dialogs I create. (there are lots of similar use cases around ad-hoc inclusion of the various declarative assets).

Control of who gets to edit the uncompiled files in my package is not a core use case currently, and is something to consider in the future if users asked for it.

**Comment by clearab** [comment] 2021-04-20 22:29
Sorry - I was totally wrong on the inclusion of ad-hoc files. Everything in the /exported folder is getting copied over correctly.

**Comment by sgellock** [comment] 2021-04-21 15:14
I believe we closed on this yesterday.  If we're in agreement, can we close this issue or raise what issue(s) remain in order to close this?

**Closed** 2021-04-21 16:37 UTC
