### ISSUE TITLE
bf luis:build not handling throttling issues

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/botframework-cli#697] opened 2020-04-02 18:31 UTC
## Versions
What CLI version are you using.
@microsoft/botframework-cli/4.8.0 win32-x64 node-v12.13.0
What Nodejs version are you using
v12.13.0
What command-line interpreters are you using
```ps
bf luis:build --luConfig $luisConfigFile --authoringKey $authoringKey --suffix $environment --log --force
```
What OS are you using
Windows 10

## Describe the bug
When running `bf luis:build` with a few luis config files it fails to run the calls as it get throttled

_Requests to the versions - Delete application version Operation under LUIS Programmatic APIs v3.0-preview have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier._

Don't find a way to upgrade the authoring resource either in Azure. Only option is the free one(For authoring resource).

Believe the cli should at least wait and retry after when the throttling has reset(next second in this case)
## To Reproduce
Run `bf luis:build` with a config file with a few `lu`
```json

"models": [
    "luis.lu",
    "loc/de-DE/luis.lu",
    "loc/es-ES/luis.lu",
    "loc/es-MX/luis.lu",
    "loc/fr-CA/luis.lu",
    "loc/fr-FR/luis.lu",
    "loc/it-IT/luis.lu",
    "loc/nl-NL/luis.lu",
    "loc/zh-CN/luis.lu"
  ]
``` 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment] 2020-04-02 22:55
@feich-ms I also saw this once in composer. We should consider baking in retry (up to 5 times) each after 1500ms, 2000ms, 2500ms, 3000ms, 3000ms before failing on a specific operation. With this, we could switch back the default timeout from 1200ms to 1000ms?

**Comment by feich-ms** [comment] 2020-04-02 23:38
Sure, make sense, will take a look.

**Comment by timotheeguerin** [comment] 2020-04-03 20:47
Do you have any workaround in the meantime that could be used? I guess I run build per language one after the other but this wouldn't have the single generated settings.json file with all the language to app id mapping

**Comment by vishwacsena** [comment] 2020-04-03 21:13
@timotheeguerin Yes. You could try to build one per language. And as you called out, with this work around you will have to manually assemble the settings.json to stitch the IDs across languages together. 

@feich-ms can you suggest any other workarounds?

**Comment by feich-ms** [comment] 2020-04-07 03:42
The only workarounds I can think out is to set deleteOldVersion to false in your luConfigFile. The issue is caused by missing waiting a time duration before deleting luis version api calls. The fix PR is very simple. It's here https://github.com/microsoft/botframework-cli/pull/704. @Vishwacsena, retry seems not necessary in current solution of concurrency implementation because it can guarantee the rate limit. This bug is caused by my mistake of missing a line, not the solution itself I think.

**Comment by feich-ms** [comment] 2020-04-13 01:40
closed since the fix PR merged

**Closed by feich-ms** 2020-04-13 01:40 UTC
Labels: R9, lu
