### ISSUE TITLE
Bot Framework CLI - Cognitive models 'Remote To Local' command issues

### ISSUE THREAD

**Issue by SharmaHarsh7** [microsoft/botframework-cli#1242] opened 2021-06-15 06:16 UTC
## Versions
What CLI version are you using : **2.24.2**
What Nodejs version are you using: **14.17.0**
What command-line interpreters are you using: **Power-shell Core 7**
What OS are you using: **Windows 10**

## Describe the bug
I am using MS Virtual Assistant Template for my bot development project.

When I ran the command './deployment/scritps/update_cognitive_models.ps1 -RemoteToLocal', it gives me below warning:
![image](https://user-images.githubusercontent.com/8860380/122002177-09b95f80-cdcf-11eb-9702-f492f7cd7062.png)

## To Reproduce
Already mentioned above.
 
## Expected behavior
Should not give any error/warning.

[bug]

**Comment by thomas-chung** [comment] 2021-06-15 18:12
Hi @SharmaHarsh7 thanks for reporting the issue! Currently we are triaging the issue. For clarity sake, did the script succeeded in execution at the end?

**Comment by SharmaHarsh7** [comment] 2021-06-16 06:55
No, we are still facing the same issue and because of this Dispatch and QnA KBs are not getting updated.

Completely blocked now.

**Comment by thomas-chung** [comment] 2021-06-17 16:55
Thanks @SharmaHarsh7. I have taken a look and the issue doesn't seem to be relating to the script itself. Internally we run _bf qnamaker:kb:export_ and based on the output of the error (converting circular structure to JSON) and this could be an issue with some of the json serialization/deserialization within bf cli. Please give me a couple hours, I will follow up with our counterparts in BF CLI team to look into this.

**Comment by thomas-chung** [comment] 2021-06-17 17:13
@munozemilio Can you please help take a look here? BF CLI seems to be choking on certain json here. Also the version of the bf cli is from a long time ago (2.24.2, latest is 4.13). So I wonder if there are bug fixes since that could have eliminate this.

**Comment by SharmaHarsh7** [comment] 2021-06-18 09:58
I investigated the issue further and got below error:

command : bot qnamaker:init

![image](https://user-images.githubusercontent.com/8860380/122543784-c880b400-d049-11eb-8dcf-ce96cad7efb4.png)

**Comment by munozemilio** [comment] 2021-06-22 04:57
Hello @SharmaHarsh7 thanks for reporting this, at the moment bf cli does not support Nodejs >= 14.
We will support it in the upcoming release. I will close this bug since this is a duplicate of #1059

**Closed by munozemilio** 2021-06-22 04:57 UTC
Labels: Bot Services, bug, customer-reported
