### ISSUE TITLE
Orchestrator create: parsing lu file fails if ML entity has same name as pattern

### ISSUE THREAD

**Issue by sibbl** [microsoft/botframework-cli#1280] opened 2021-08-03 15:09 UTC
## Versions
What CLI version are you using: 4.14.1
What Nodejs version are you using: 14.16.0
What command-line interpreters are you using: `bf orchestrator:create`
What OS are you using: Windows 10

## Describe the bug
We do have a valid and working LUIS app which has an `Address` ML entity which contains a child `Name`. 
Besides, we do have a `patternany` entity which is also called `Name`.

Everything works fine in LUIS and the results are working fine.

However, creating an orchestrator label resolver snapshot fails when using `bf orchestrator:create`.

Please find very minimal a sample with a sample lu file attached: 
[orchestrator-demo.zip](https://github.com/microsoft/botframework-cli/files/6925109/orchestrator-demo.zip)

## To Reproduce
1. Download and unzip the demo file
2. Next to the `orchestratorsettings.json`, download any basemodel into the existing and empty `model` folder
3. Run `bf orchestrator:create`

## Expected behavior
The label resolver snapshot is created and saved properly.

## Current behavior
The command fails with
```
[2021-08-03T14:58:51.087Z] LOG-MESSAGE: "read to call LabelResolver.setRuntimeParams(), fullEmbeddings=false"
[2021-08-03T14:58:51.087Z] LOG-MESSAGE: "read to call LabelResolver.setRuntimeParams(), resetAll=false"
[2021-08-03T14:58:51.087Z] LOG-MESSAGE: "read to call LabelResolver.setRuntimeParams(), useCompactEmbeddingsObject=[object Object]"
[2021-08-03T14:58:51.087Z] LOG-MESSAGE: "read to call LabelResolver.setRuntimeParams(), useCompactEmbeddingsObject.use_compact_embeddings=true"
[2021-08-03T14:58:51.087Z] LOG-MESSAGE: "read to call LabelResolver.setRuntimeParams(), useCompactEmbeddingsObjectJson={\n    \"use_compact_embeddings\": true\n}"
[2021-08-03T14:58:51.088Z] LOG-MESSAGE: "read to call Utility.getConfigJson(), LabelResolver.LabelResolver=[object Object]"
Processing C:\Temp\orchestrator-demo\dataSources\sample.lu...Failed to parse C:\Temp\orchestrator-demo\dataSources\sample.lu
```

Please note that I've created a new LUIS app from scratch and exported the LU file from the LUIS website.

[bug]

**Comment by benbrown** [comment] 2021-08-04 18:08
@munozemilio can you take a look here?

**Comment by hcyang** [comment] 2021-08-05 02:54
Hi @sibbl,

There is an error parsing the input file, 'sample.lu' 
The following non-Orchestrator command cannot succeed, either.
Please use a different name. We will improve the error message, but I will close the issue for now as it's not a bug, the issue is well understood, and there is an easy workaround. Feel free to comment and/or reopen the issue.

bf luis:convert --in .\dataSources\sample.lu --out experiment_training

Patterns cannot contain references to child entities. Pattern: "foo bar {Name}" has reference to "{Name}".

**Closed by hcyang** 2021-08-05 02:54 UTC
Labels: Bot Services, bug, customer-reported, needs-triage
