### ISSUE TITLE
Invalid LUIS JSON file content.

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/botframework-cli#588] opened 2020-02-19 15:02 UTC
## Versions
CLI version  4.7.0
Nodejs version 13.9.0
command-line interpreter pwsh.exe
OS Windows 10

## Describe the bug
luis:generate:cs fails with error "Invalid LUIS JSON file content."
The json file looks good to me
[AccountServices.json.txt](https://github.com/microsoft/botframework-cli/files/4226267/AccountServices.json.txt)

## To Reproduce
1. Go to luis.ai. create a new app with a single intent
2. run bf luis:version:export
3. run bf luis:generate:cs

## Expected behavior
cs file is generated

## Screenshots
![image](https://user-images.githubusercontent.com/20775323/74846696-8b41d000-52f6-11ea-9a2a-606f5aba1f35.png)

[bug]

**Comment by turbozapekanka** [comment] 2020-02-19 17:31
Note it works if I export the JSON from the luis.ai website

**Comment by axelsrz** [comment] 2020-02-20 23:17
This is a duplicate of #453 
@turbozapekanka I've noticed that the schema file you're mentioning is v6.0.0 luisgen currently only supports v4.

**Closed by axelsrz** 2020-02-20 23:17 UTC
Labels: Bot Services, R8, customer-reported
