### ISSUE TITLE
bf luis:build is failing with error message which is not actionable. (Buffer cannot be null)

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-cli#1006] opened 2020-10-07 17:50 UTC
## Versions
4.10

## Describe the bug
Trying to build a model is failing with "Buffer cannot be null"

## To Reproduce
```
bf luis:build --botName MSMeeting-Actions --authoringKey {REDACTED}--region westus --in Composer --out Composer/generated --dialog=multiLanguage --suffix Test --log
```
The output is
```
[WARN] line 206:0 - line 206:7: no utterances found for intent definition: "# None"
Handling applications...
[WARN]: empty intent(s) # None are filtered when handling luis application
Buffer cannot be null. Parameter name: buffer
```
## Expected behavior
To give me info so I can know how to fix my model

[msmeeting-actions.en-us.lu.txt](https://github.com/microsoft/botframework-cli/files/5342770/msmeeting-actions.en-us.lu.txt)

[bug]

**Comment by feich-ms** [comment] 2020-10-09 09:09
@tomlm, thanks for reporting this issue. I tried the command and lu file you provided with 4.10.1 bf cli, but cannot reproduce this error. Below is the screenshot of my testing. Did I miss any other steps to reproduce it? Or could you give more specific repro steps?

![image](https://user-images.githubusercontent.com/43032123/95564432-5df68d80-0a51-11eb-9e6f-aa68e036a4e9.png)

**Comment by feich-ms** [comment] 2020-10-13 06:26
Close this first since it's not reproduceable. Please reopen it again if running into this error later.

**Closed by feich-ms** 2020-10-13 06:26 UTC
