### ISSUE TITLE
luis:generate:cs generates illegal c#

### ISSUE THREAD

**Issue by jbgh2** [microsoft/botframework-cli#640] opened 2020-03-05 22:15 UTC
## Versions
What CLI version are you using: @microsoft/botframework-cli/4.7.0 win32-x64 node-v12.14.1
What Nodejs version are you using: v12.14.1
What command-line interpreters are you using: terminal
What OS are you using: Windows 10

## Describe the bug

luis:generate:cs generates illegal cs for a model exported from preview.luis.ai

## To Reproduce
1. Download ToolError.json from [Generator error.zip](https://github.com/microsoft/botframework-cli/files/4295381/Generator.error.zip)

2. Run command: luis:generate:cs --in ToolError.json --out ToolError.cs --className=namespace.ignored.testclass -f

3. Open ToolError.cs

4. Note illegal C# code 

## Expected behavior

Tool can generate valid c# for JSON produced by luis.ai

## Additional context

[bug]

**Comment by axelsrz** [comment] 2020-03-06 17:51
This is a duplicate of #453

**Closed by axelsrz** 2020-03-06 17:51 UTC
Labels: Bot Services, customer-replied-to, customer-reported
