### ISSUE TITLE
botskills refresh can't be run in PowerShell task of Azure DevOps release pipelines

### ISSUE THREAD

**Issue by ericchansen** [microsoft/botframework-cli#1023] opened 2020-10-16 20:50 UTC
## Versions

Using Azure pipelines.

Agent pool: Azure Pipelines
Agent Specification: vs2017-win2016

## Describe the bug

Can't successfully use `botskills refresh --cs ./path/to/cognitivemodels.json --dispatchFolder ./path/to/Deployment/Resources/dispatch` in Azure pipelines.

## To Reproduce

1. Create a template Bot Framework Virtual Assistant
2. In the release pipeline, install the pre-requisite npm tools and attempt to use `botskills refresh --cs ./path/to/cognitivemodels.json --dispatchFolder ./path/to/Deployment/Resources/dispatch`.

Regardless of how you install the required npm packages, it will not work. You will get an error similar to this.

```
2020-10-16T20:44:18.2228935Z }
2020-10-16T20:44:18.2397954Z Running Luis Generate for Masteren-us...
2020-10-16T20:44:18.2400791Z Executing luisgen for the Masteren-us file
2020-10-16T20:44:21.3236825Z There was an error while refreshing any Skill from the Assistant:
2020-10-16T20:44:21.3238398Z Error: There was an error in the bf luis:generate:cs command:
2020-10-16T20:44:21.3240619Z Command: bf luis:generate:cs --in "D:\a\r1\a\_source\Coned.Core\Coned.Core\Coned.Core\Deployment\Resources\dispatch\qa\en-us\Masteren-us.json" --out "D:\a\r1\a\Services\DispatchLuis.cs" --className DispatchLuis --force
2020-10-16T20:44:21.3242335Z Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues
2020-10-16T20:44:21.3243144Z undefined
2020-10-16T20:44:21.3243507Z 
```

## Expected behavior

Same results as local, where everything works just fine.

## Additional context

* Duplicated issue here https://github.com/microsoft/botbuilder-tools/issues/1475.

[bug]

**Comment by stevengum** [comment] 2020-10-19 18:39
Closing issue as it is a duplicate of microsoft/botbuilder-tools#1475. @ericchansen we will track the bug report and any fixes in that issue.

**Closed by stevengum** 2020-10-19 18:39 UTC
