### ISSUE TITLE
QNAMaker-CLI Multi-turn Prompts not working

### ISSUE THREAD

**Issue by hhasenauer** [microsoft/botframework-cli#748] opened 2020-05-05 10:34 UTC
## Versions
- CLI  @microsoft/botframework-cli/4.8.0 darwin-x64 node-v13.9.0
- OS macOS Catalina 10.15.4 (19E287)

## Describe the bug
bf qnamaker:kb:replace not working for multi-turn prompts.

## How to reproduce
1. Create a Multi Turn Prompt in the [QNAMaker portal](https://www.qnamaker.ai/).
1. Export the QNAMaker model 
`bf qnamaker:kb:export --kbId x --subscriptionKey x --endpoint https://westus.api.cognitive.microsoft.com/qnamaker/v4.0 > demo.json`
1. Check the demo.json and verify that the multi-turn prompt got exported.
```json
{
      "id": 841,
      "answer": "Yes this is a demo!",
      "source": "custom editorial",
      "questions": [
        "Demo?"
      ],
      "metadata": [],
      "alternateQuestionClusters": [],
      "context": {
        "isContextOnly": false,
        "prompts": [
          {
            "displayOrder": 0,
            "qnaId": 873,
            "displayText": "yes"
          },
          {
            "displayOrder": 0,
            "qnaId": 874,
            "displayText": "no"
          }
        ]
      }
    }
```
4. Now try to replace the model on QNAMaker with the exported json.
`bf qnamaker:kb:replace --in ./demo.json --kbId x --subscriptionKey x --endpoint https://westus.api.cognitive.microsoft.com/qnamaker/v4.0`
5. Check in the QNAMaker portal and see that the multi-turn prompt is gone.

[bug]

**Comment by vipeketi** [comment] 2020-05-07 17:19
@cleemullins  @pchoudhari  Acknowledging Issue.

**Comment by vipeketi** [comment] 2020-05-08 07:18
@hhasenauer multiturn export and import work fine. I have verified. Please make sure that the qna definitons are available for qnaid value , provided in prompts.

**Comment by hhasenauer** [comment] 2020-05-11 14:35
@vipeketi I created a minimal sample for a .json, that does not work for me.
Can you help me, what I am missing there? qnaId **does** match the ids of the corresponding questions.

```json
{
    "qnaDocuments": [{
            "id": 1,
            "answer": "demoanswer",
            "source": "custom editorial",
            "questions": [
                "test"
            ],
            "metadata": [],
            "alternateQuestionClusters": [],
            "context": {
                "isContextOnly": false,
                "prompts": [{
                        "displayOrder": 0,
                        "qnaId": 2,
                        "displayText": "yes"
                    },
                    {
                        "displayOrder": 1,
                        "qnaId": 3,
                        "displayText": "no"
                    }
                ]
            }
        },
        {
            "id": 2,
            "answer": "yesanswer",
            "source": "custom editorial",
            "questions": [
                "yes"
            ],
            "metadata": [],
            "alternateQuestionClusters": [],
            "context": {
                "isContextOnly": false,
                "prompts": []
            }
        },
        {
            "id": 3,
            "answer": "noanswer",
            "source": "custom editorial",
            "questions": [
                "no"
            ],
            "metadata": [],
            "alternateQuestionClusters": [],
            "context": {
                "isContextOnly": false,
                "prompts": []
            }
        }
    ]
}
```

Furthermore I tried multiple times to create a correct prompt on the portal and then export it and directly import it again. Which leads to all prompts disappearing.

**Comment by vipeketi** [comment] 2020-05-11 14:41
@hhasenauer    please provide knowledgebase id. It will help me debug.

**Comment by hhasenauer** [comment] 2020-05-11 14:58
kbId: 8825453e-0f0e-4800-9138-9609376b40ba 
currently in the state where the prompts are not present anymore because I imported the json.

**Comment by cleemullins** [comment] 2020-05-13 18:18
@vipeketi, any update here?

**Comment by vipeketi** [comment] 2020-05-14 07:56
@hhasenauer @cleemullins  I will try to close this by friday.

**Comment by vipeketi** [comment] 2020-05-14 18:08
@hhasenauer Not all the times, Id of QnA is restored, to as that of provided in import definition during import. The sequential id number which is next to last qnaid previously available in KB,  is used for sequentially numbering QnAs. Hence it is recommended to change the id during import, to restore prompts.

**Comment by hhasenauer** [comment] 2020-05-26 07:03
So the solution would be to manually increment and manage all IDs in the KB?

**Comment by vipeketi** [comment] 2020-05-27 11:34
@hhasenauer I have downloaded a kb with multiturn information in tsv format, modified the prompts and uploaded again in tsv format. This test worked well. Prompts updates are reflected in KB. Would you like to try this option.

**Comment by hhasenauer** [comment] 2020-05-29 12:10
@vipeketi Unfortunately that is not an option for me. I want all my language models for this chat bot project in .lu and .qna files. And therefore also define the multi-turn prompts within those files. And the ludown cli does compile it to .json only.
Do you have any idea for a valid workaround for now?

**Comment by vipeketi** [comment] 2020-05-29 18:13
@hhasenauer Acknowledge issue.

**Comment by vipeketi** [comment] 2020-06-04 12:52
@hhasenauer I could reproduce issue with version CLI @microsoft/botframework-cli/4.8.0. Please use CLI @microsoft/botframework-cli/4.9.1. The issue is fixed.

**Closed** 2020-06-09 18:14 UTC
Labels: Bot Services, customer-replied-to, customer-reported
