### ISSUE TITLE
When try to create orchestator snapshot file I am getting following error

### ISSUE THREAD

**Issue by sreejithrkknd** [microsoft/botframework-cli#1275] opened 2021-07-23 06:20 UTC
## Versions
What CLI version are you using- latest
What Nodejs version are you using- latest
What command-line interpreters are you using 
What OS are you using- windows

## Describe the bug
2021-07-23 11:48:35.2446284 [E:onnxruntime:, inference_session.cc:1294 onnxruntime::InferenceSession::Initialize::<lambda_14ab80433efd07306ceb190544d07c3a>::operator ()] Exception during initialization: bad allocation
EXCEPTION THROWN - utility_onnx::OnnxUtility::InitOnnxSession(): e.what()=Exception during initialization: bad allocation, __FILE__=D:\a\1\s\oc\utility\OnnxUtility.h, __LINE__=117
EXCEPTION THROWN - OC - EmbedderBase::EmbedderBase(json const& config, const string onnxVocabFileDefault, const string onnxModelFileDefault): e.what()=Exception during initialization: bad allocation, FILE=D:\a\1\s\oc\EmbedderBase.cc, LINE=57
Exception during initialization: bad allocation

## To Reproduce
execute this command- bf orchestrator:create --hierarchical --in ./CognitiveModels --out ./generated --model ./model
tried JSON and .lu files

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by taicchoumsft** [comment] 2021-07-26 18:12
@tsuwandy , @hcyang , you guys recently saw and diagnosed this issue in a IcM, do you guys have any input here?

**Comment by tsuwandy** [comment] 2021-07-26 18:35
@sreejithrkknd, could you delete everything in model folder and redownload the base model with bf orchestrator:basemodel:get command? 

Try the create command and let us know if you are getting the same error.

**Comment by hcyang** [comment] 2021-07-26 20:27
The "bad allocation" error was simply that Orchestrator cannot allocate enough memory from the running machine for loading a base model. It can be resolved by ensuring sufficient memory bandwidth, such as cancelling some memory-hogging processes or using a machine with more physical memory, etc. We have seen this issue from an internal issue report. @sreejithrkknd, please use Task Manager or similar tools to monitor memory consumption.

**Comment by sreejithrkknd** [comment] 2021-07-27 06:02
> @sreejithrkknd, could you delete everything in model folder and redownload the base model with bf orchestrator:basemodel:get command?
> 
> Try the create command and let us know if you are getting the same error.
I tried these steps but not worked.

**Comment by sreejithrkknd** [comment] 2021-07-27 06:05
> The "bad allocation" error was simply that Orchestrator cannot allocate enough memory from the running machine for loading a base model. It can be resolved by ensuring sufficient memory bandwidth, such as cancelling some memory-hogging processes or using a machine with more physical memory, etc. We have seen this issue from an internal issue report. @sreejithrkknd, please use Task Manager or similar tools to monitor memory consumption.

My pc is having enough memory. It is not related to memoryif I perform the command 7 or 8 times maybe it will work. sometimes doesn't. I tried restart also sometimes it will work but it's not a permanent solution

**Comment by hcyang** [comment] 2021-07-27 08:32
Hi @sreejithrkknd, please provide your hardware configuration, especially the memory size. Please provide the screenshot of Task Manager's memory utilization before you ran the "create" command.
I noticed that you were using Windows, were you using bf-cli x86 or x64 build?
Please run 'bf --version' and report the version output.
Please also provide the model version/key unless you were using the default base models (no model version/key provided to the "create" command).
Please list the files in ./model as well as the file content of .\model\config.json.

The "bad allocation" error message came directly from C++'s memory allocation code (https://www.geeksforgeeks.org/bad_alloc-in-cpp/, https://stackoverflow.com/questions/4615021/bad-allocation-exceptions-in-c, http://www.cplusplus.com/reference/new/bad_alloc/).

**Comment by sreejithrkknd** [comment] 2021-07-28 07:01
![image](https://user-images.githubusercontent.com/87656788/127278162-d63621ae-4675-414f-8afb-8f5615e5c752.png)
bf version- @microsoft/botframework-cli/4.14.1 win32-x86 node-v14.17.3
using default model

model- config.json
{
  "VocabFile": "vocab.txt",
  "ModelFile": "model.onnx",
  "Name": "pretrained.20200924.microsoft.dte.00.06.en.onnx",
  "Framework": "onnx",
  "Publisher": "Microsoft",
  "ModelType": "dte_bert",
  "Layers": 6,
  "EmbedderVersion": 1,
  "MinRequiredCoreVersion": "1.0.0"
}

files in the model folder
![image](https://user-images.githubusercontent.com/87656788/127278442-82ac85c4-11bf-47e7-ba90-442583817d02.png)

**Comment by hcyang** [comment] 2021-07-28 08:11
Hi @sreejithrkknd, the Task Manager memory screenshot was taken before you tried to run the "create" command, right? Looks like your machine has very little free space left for allocating a base model, model.onnx. Even though its disk size is about 261MB, but it would require a contiguous and larger space in main memory to be de-serialized. If you don't have a machine with more memory, then you can try to use smaller models. See below. Both are smaller, thus may not perform as good as the default 6-layer model.
The first is a 3-layer model, while the second is the 6-layer (same as the default) but with parameters/weights quantized.

pretrained.20200924.microsoft.dte.00.03.en.onnx
pretrained.20210521.microsoft.dte.01.06.int.en.onnx

BTW, you can list all the available models using the command below

bf orchestrator:basemodel:list --all

Also, I think your 8GB machine should still be able to run the "create" command using the default model, if you can cut down memory consumption by stopping some tasks/processes.

**Comment by daveta** [comment] 2021-07-28 19:56
Hi @sreejithrkknd, Btw - it's recommended in production, you run with x64 hosts.

**Comment by hcyang** [comment] 2021-07-28 20:47
Hi @sreejithrkknd, I am going to close the issue as the problem is well understood and there are plenty of solutions and workarounds to mitigate your situation. Feel free to discuss the issue with us in the future.

**Closed by hcyang** 2021-07-28 20:47 UTC
Labels: Area: AI-Orchestrator, Bot Services, customer-replied-to, customer-reported

**Comment by rohansainiCT** [comment] 2021-08-11 09:33
I am same issue on app service. This app service is on S1.

TypeError: Exception during initialization: bad allocation
    at OrchestratorRecognizer._initializeModel (C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\lib\orchestratorRecognizer.js:272:35)
    at OrchestratorRecognizer.<anonymous> (C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\lib\orchestratorRecognizer.js:143:18)
    at Generator.next (<anonymous>)
    at C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\lib\orchestratorRecognizer.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\lib\orchestratorRecognizer.js:11:12)
    at OrchestratorRecognizer.recognize (C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\lib\orchestratorRecognizer.js:123:16)
    at MainDispatcher.callLuis (C:\home\site\wwwroot\Dispatcher\mainDispatcher.js:321:68)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by hcyang** [comment] 2021-08-11 17:21
Hi @rohansainiCT, the Azure App Service S1 only offer 1.75GB of RAM, so it's a bit tiny (see the attached image). What model did you try to run? Can you try using the smaller models as suggested (and see the list below)? Thanks.

pretrained.20200924.microsoft.dte.00.03.en.onnx
pretrained.20210521.microsoft.dte.01.06.int.en.onnx

![image](https://user-images.githubusercontent.com/370110/129074272-cabb9431-f57a-4c26-9dce-39e625882eca.png)

**Comment by rohansainiCT** [comment] 2021-09-02 08:10
> Hi @rohansainiCT, the Azure App Service S1 only offer 1.75GB of RAM, so it's a bit tiny (see the attached image). What model did you try to run? Can you try using the smaller models as suggested (and see the list below)? Thanks.
> 
> pretrained.20200924.microsoft.dte.00.03.en.onnx
> pretrained.20210521.microsoft.dte.01.06.int.en.onnx
> 
> ![image](https://user-images.githubusercontent.com/370110/129074272-cabb9431-f57a-4c26-9dce-39e625882eca.png)

Any change in English base model as compared to multilingual models

**Comment by hcyang** [comment] 2021-09-02 16:17
Hi @rohansainiCT, EN-only models are optimized specifically for EN-only scenarios, so its vocabulary is small, containing mostly English tokens. Multilingual models can apply to any language and have a much bigger vocabulary. We have some internal performance tracking of Orchestrator default models, but the performance numbers may vary datasets to datasets. In short, please try them out on your datasets. Thanks.
