### ISSUE TITLE
Mac M1 (arm64) not supported

### ISSUE THREAD

**Issue by agvglobant** [microsoft/botframework-cli#1380] opened 2024-06-26 16:32 UTC
Hi, i'm trying to install with NPM with:

npm i -g @microsoft/botframework-cli

And it fails with:

npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@microsoft/bf-orchestrator-cli@4.16.0-dev.20231122.4561d55',
npm warn EBADENGINE   required: { node: '^10.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0' },
npm warn EBADENGINE   current: { node: 'v20.14.0', npm: '10.8.1' }
npm warn EBADENGINE }
npm error code EBADPLATFORM
npm error notsup Unsupported platform for @microsoft/bf-orchestrator-cli@4.16.0-dev.20231122.4561d55: wanted {"os":"darwin,linux,win32","cpu":"x64,ia32"} (current: {"os":"darwin","cpu":"arm64"})
npm error notsup Valid os:   darwin,linux,win32
npm error notsup Actual os:  darwin
npm error notsup Valid cpu:  x64,ia32
npm error notsup Actual cpu: arm64

Is this saying arm64 cpu is not supported? Is it? 

Running under MacOS Sonoma 14.5

Thanks,

**Comment by agvglobant** [comment] 2024-06-26 17:46
As suggested, I have tryied running the npm command in iTerm2 (under Rosetta2 emulation) but the error persists (exact same error).

**Comment by dmvtech** [comment] 2024-06-26 20:08
Closing as a duplicate of https://github.com/microsoft/botframework-cli/issues/1315

Please try the workaround suggested there. If you need further assistance, please comment on that issue.

**Closed by dmvtech** 2024-06-26 20:08 UTC
Labels: bug, needs-triage
